business_name: "555Beatbox Academy Singapore"
bot_name: "Luke.AI"

# LLM Provider Configuration
llm:
  # Provider: "groq", "openai", or "anthropic"
  provider: "groq"

  # Model name (leave empty for default)
  # Groq: llama-3.3-70b-versatile
  # OpenAI: "gpt-3.5-turbo", "gpt-4o", "gpt-4-turbo-preview"
  # Anthropic: "claude-3-haiku-20240307", "claude-3-sonnet-20240229", "claude-3-opus-20240229"
  model: "llama-3.3-70b-versatile"

  # Or use tier: "fast", "balanced", or "powerful" (auto-selects model for provider)
  # tier: "balanced"

# Business description for conversational AI
business_description: |
  555Beatbox Academy Singapore offers beatboxing classes for kids and teens.

  KIDS CLASS (Ages 4-12):
  - Weekend at Bendemeer (nearest MRT: Boon Keng)
    Address: 994 Bendemeer Road #02-06
    Timeslots: Saturday 3-4pm, Sunday 12-1pm, Sunday 1-2pm, Sunday 3-4pm
  - Weekday at Bras Basah (nearest MRT: Bencoolen)
    Address: 261 Waterloo Street #04-37
    Timeslots: Friday 3-4pm
  - Trial: $10
  - Class size: 2-10 kids (Sundays usually have more)

  TEENS CLASS (Ages 13-16):
  - Sunday 2-3pm at Bendemeer

  PRIVATE CLASS (Flexible):
  - $50/class (block of 4 = $200)
  - Instructor can travel
  - Flexible schedule based on instructor availability

  PRICING (SGD):
  - Weekend: $40/class (~$160/month, can be $200 if 5 weeks)
  - Weekday: $30/class (~$120/month, can be $150 if 5 weeks)

  PAYMENT POLICY:
  - Monthly basis
  - Finance team checks which days child can attend before each month
  - Once attendance confirmed, no refunds
  - Missed classes get make-up class in another slot

  SPECIAL NOTES:
  - Ages 1-3: Too young but we provide extra assistance
  - ADHD/ASD: Suggest trial first; if group not suitable, recommend private 1-on-1
  - Performance enquiries: Artist manager Ryan will contact them

# Response templates - use {name} placeholder for personalization
reply_on_intent_detected: "Hi {name}! It looks like you're interested in joining our beatboxing kids class. Should I go ahead and register your information?"
reply_on_success: "Awesome {name}! You're officially registered for our next beatboxing kids class. We'll reach out soon with more details!"
reply_on_rejection: "No problem {name}! Feel free to reach out anytime if you change your mind. We'd love to have you join us!"
reply_on_neutral: "Hey {name}! Want to learn some cool beatboxing skills? I can help you sign up when you're ready."
reply_on_unclear: "Sorry {name}, I didn't quite understand. Could you please confirm with 'yes' or 'no'?"

# Intent detection keywords (optional - mainly for reference, LLM does the actual detection)
intent:
  include_keywords: ["join", "sign up", "register", "enroll", "class", "lesson", "interested"]
  exclude_keywords: ["cancel", "not interested", "refund", "price"]

# Confirmation keywords
confirmation:
  positive: ["yes", "yeah", "yep", "sure", "ok", "okay", "confirm", "correct", "right", "absolutely", "definitely"]
  negative: ["no", "nope", "nah", "cancel", "stop", "never mind", "nevermind", "not interested"]

# Conversation settings
conversation:
  # How often to suggest booking (every N messages). Set to 0 to never auto-suggest
  booking_suggestion_frequency: 2
  # Be pushy about collecting age?
  pushy_age_collection: false
