business_name: "555Beatbox Academy Singapore"
bot_name: "Luke.AI"

# LLM Provider Configuration
llm:
  # Provider: "groq", "openai", or "anthropic"
  provider: "groq"

  # Model name (leave empty for default)
  # Groq: llama-3.3-70b-versatile
  # OpenAI: "gpt-3.5-turbo", "gpt-4o", "gpt-4-turbo-preview"
  # Anthropic: "claude-3-haiku-20240307", "claude-3-sonnet-20240229", "claude-3-opus-20240229"
  model: "llama-3.1-8b-instant"

  # Or use tier: "fast", "balanced", or "powerful" (auto-selects model for provider)
  # tier: "balanced"

# Business description for conversational AI
business_description: |
  555Beatbox Academy Singapore offers beatboxing classes for kids and teens.

  KIDS CLASS (Ages 4-12):
  - Weekend at Bendemeer (nearest MRT: Boon Keng)
    Address: 994 Bendemeer Road #02-06
    Timeslots: Saturday 3-4pm, Sunday 12-1pm, Sunday 1-2pm, Sunday 3-4pm
  - Weekday at Bras Basah (nearest MRT: Bencoolen)
    Address: 261 Waterloo Street #04-37
    Timeslots: Friday 3-4pm
  - Trial: $10
  - Class size: 2-10 kids (Sundays usually have more)

  TEENS CLASS (Ages 13-16):
  - Sunday 2-3pm at Bendemeer

  PRIVATE CLASS (Flexible):
  - $50/class (block of 4 = $200)
  - Instructor can travel
  - Flexible schedule based on instructor availability

  PRICING (SGD):
  - Weekend: $40/class (~$160/month, can be $200 if 5 weeks)
  - Weekday: $30/class (~$120/month, can be $150 if 5 weeks)

  PAYMENT POLICY:
  - Monthly basis
  - Finance team checks which days child can attend before each month
  - Once attendance confirmed, no refunds
  - Missed classes get make-up class in another slot

  SPECIAL NOTES:
  - Ages 1-3: Too young but we provide extra assistance
  - ADHD/ASD: Suggest trial first; if group not suitable, recommend private 1-on-1
  - Performance enquiries: Artist manager Ryan will contact them

# Intent detection keywords (optional - mainly for reference, LLM does the actual detection)
intent:
  include_keywords: ["join", "sign up", "register", "enroll", "class", "lesson", "interested"]
  exclude_keywords: ["cancel", "not interested", "refund", "price"]

# Conversation settings
conversation:
  # How often to suggest booking (every N messages). Set to 0 to never auto-suggest
  booking_suggestion_frequency: 2
  # Be pushy about collecting age?
  pushy_age_collection: false

  # Progressive booking data collection (extracts info as conversation progresses)
  progressive_data_collection: true  # Enable progressive extraction
  extraction_method: "hybrid"  # Options: "regex" (fast), "llm" (accurate), "hybrid" (recommended)

# Booking data extraction configuration
booking_fields:
  # Indicators that a booking summary is present
  summary_indicators: ["Booking Details:", "📝"]

  # Confirmation trigger phrases
  confirmation_triggers: ["BOOKING_CONFIRMED", "**BOOKING_CONFIRMED**"]

  # Field definitions for extraction
  fields:
    - name: "Parent Name"
      patterns: ["Parent Name", "Parent's Name", "Your Name"]
      required: true

    - name: "Child Name"
      patterns: ["Child Name", "Student Name", "Kid's Name"]
      required: true

    - name: "Child Age"
      patterns: ["Child Age", "Age", "Student Age"]
      required: true

    - name: "Contact"
      patterns: ["Contact", "Phone", "Mobile", "Contact Number"]
      required: true

    - name: "Email"
      patterns: ["Email", "Email Address", "E-mail"]
      required: true

    - name: "Timeslot"
      patterns: ["Timeslot", "Time Slot", "Time", "Schedule"]
      required: true

    - name: "Date"
      patterns: ["Date", "Start Date", "Trial Date"]
      required: true

    - name: "Location"
      patterns: ["Location", "Venue", "Address"]
      required: true

    - name: "Timestamp"
      auto_generate: true  # Automatically generated, not extracted

  # Essential fields that MUST be present for booking to be valid
  essential_fields: ["Parent Name", "Contact", "Timeslot"]
